


  CREATE TABLE "P_MESA" 
   (	"IDMESA" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NUMMAXCOMENSALES" NUMBER(*,0), 
	"UBICACION" VARCHAR2(20 BYTE), 
	 CONSTRAINT "P_MESA_PK" PRIMARY KEY ("IDMESA")
   );
   
     CREATE TABLE "P_COCINERO" 
   (	"IDCOCINERO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"APELLIDO1" VARCHAR2(20 BYTE), 
	"APELLIDO2" VARCHAR2(20 BYTE), 
	 CONSTRAINT "P_COCINERO_PK" PRIMARY KEY ("IDCOCINERO")
   );

  CREATE TABLE "P_CAMARERO" 
   (	"IDCAMARERO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"APELLIDO1" VARCHAR2(20 BYTE), 
	"APELLIDO2" VARCHAR2(20 BYTE), 
	 CONSTRAINT "P_CAMARERO_PK" PRIMARY KEY ("IDCAMARERO")
   );
   
     CREATE TABLE "P_CLIENTE" 
   (	"IDCLIENTE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"APELLIDO1" VARCHAR2(20 BYTE), 
	"APELLIDO2" VARCHAR2(20 BYTE), 
	"OBSERVACIONES" VARCHAR2(200 BYTE), 
	 CONSTRAINT "P_CLIENTE_PK" PRIMARY KEY ("IDCLIENTE")
   );
   
   
        CREATE TABLE "P_FACTURA" 
   (	"IDFACTURA" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"IDCLIENTE" VARCHAR2(20 BYTE), 
	"IDCAMARERO" VARCHAR2(20 BYTE), 
	"IDMESA" VARCHAR2(20 BYTE), 
	"FECHAFACTURA" DATE, 
	 CONSTRAINT "P_FACTURA_PK" PRIMARY KEY ("IDFACTURA") ENABLE, 
	 CONSTRAINT "P_FACTURA_CAMARERO" FOREIGN KEY ("IDCAMARERO")
	  REFERENCES "P_CAMARERO" ("IDCAMARERO") ENABLE, 
	 CONSTRAINT "P_FACTURA_CLIENTE" FOREIGN KEY ("IDCLIENTE")
	  REFERENCES "P_CLIENTE" ("IDCLIENTE") ENABLE, 
	 CONSTRAINT "P_FACTURA_MESA" FOREIGN KEY ("IDMESA")
	  REFERENCES "P_MESA" ("IDMESA") ENABLE
   );


     CREATE TABLE "P_DETALLE_FACTURA" 
   (	"IDFACTURA" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"IDDETALLEFACTURA" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"IDCOCINERO" VARCHAR2(20 BYTE), 
	"PLATO" VARCHAR2(20 BYTE), 
	"IMPORTE" NUMBER(*,0), 
	 CONSTRAINT "P_DETALLE_FACTURA_PK" PRIMARY KEY ("IDDETALLEFACTURA") ENABLE, 
	 CONSTRAINT "P_DETALLE_FACTURA_COCINERO" FOREIGN KEY ("IDCOCINERO")
	  REFERENCES "P_COCINERO" ("IDCOCINERO") ENABLE, 
	 CONSTRAINT "P_DETALLE_FACTURA_FACTURA" FOREIGN KEY ("IDFACTURA")
	  REFERENCES "P_FACTURA" ("IDFACTURA") ENABLE
   );
   
   



Insert into P_MESA (IDMESA,NUMMAXCOMENSALES,UBICACION) values ('1','4','esquina');
Insert into P_MESA (IDMESA,NUMMAXCOMENSALES,UBICACION) values ('2','2','centro');
Insert into P_MESA (IDMESA,NUMMAXCOMENSALES,UBICACION) values ('3','3','ventana');
Insert into P_MESA (IDMESA,NUMMAXCOMENSALES,UBICACION) values ('4','6','balcon');
Insert into P_MESA (IDMESA,NUMMAXCOMENSALES,UBICACION) values ('5','5','entrada');

Insert into P_COCINERO (IDCOCINERO,NOMBRE,APELLIDO1,APELLIDO2) values ('79000000','eduardo','nova','mateus');
Insert into P_COCINERO (IDCOCINERO,NOMBRE,APELLIDO1,APELLIDO2) values ('79000001','felipe','roa','vargas');
Insert into P_COCINERO (IDCOCINERO,NOMBRE,APELLIDO1,APELLIDO2) values ('79000002','camila','montero','moreno');
Insert into P_COCINERO (IDCOCINERO,NOMBRE,APELLIDO1,APELLIDO2) values ('79000003','mario','diaz','triviño');
Insert into P_COCINERO (IDCOCINERO,NOMBRE,APELLIDO1,APELLIDO2) values ('79000004','gustavo','rojas','pinilla');

Insert into P_CAMARERO (IDCAMARERO,NOMBRE,APELLIDO1,APELLIDO2) values ('81000000','juan','vargas','roa');
Insert into P_CAMARERO (IDCAMARERO,NOMBRE,APELLIDO1,APELLIDO2) values ('81000001','diego','salas','santos');
Insert into P_CAMARERO (IDCAMARERO,NOMBRE,APELLIDO1,APELLIDO2) values ('81000002','sara','briñez','saenz');
Insert into P_CAMARERO (IDCAMARERO,NOMBRE,APELLIDO1,APELLIDO2) values ('81000003','andres','tecatito','guardado');
Insert into P_CAMARERO (IDCAMARERO,NOMBRE,APELLIDO1,APELLIDO2) values ('81000004','chris','diaz','vargas');